#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:2.2-stretch AS build
WORKDIR /src
COPY ["BDB.Api/BDB.Api.csproj", "BDB.Api/"]
RUN dotnet restore "BDB.Api/BDB.Api.csproj"
COPY . .
WORKDIR "/src/BDB.Api"
RUN dotnet build "BDB.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "BDB.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "BDB.Api.dll"]